### ISSUE TITLE
Path for migrating to ESP-IDF 5.x

### ISSUE THREAD

**Issue by faern** [cat-in-136/ws2812-esp32-rmt-driver#31]
ESP-IDF 5 is out, and `esp-idf-sys` and the entire ecosystem now supports the new IDF versions. However, in these new versions [`rmt_write_sample` is gone](https://github.com/espressif/esp-idf/blob/master/docs/en/migration-guides/release-5.x/5.0/peripherals.rst). To use this driver with the newer IDF versions, a rewrite of how the RMT interaction happens will have to take place.

I have been thinking for quite a while to reimplement this driver so it supports writing without blocking the writing thread. Maybe even support `async` Rust. This might be the time for incorporating that. ESP-IDF seem to have pretty good support for initiating a TX operation without blocking.

**Comment by faern** [comment]
I think this driver should use `esp-idf-hal` and the safe `Peripherals` abstraction. They seem to have nice RMT support. And it's better typed than giving the `channel` and `gpio_pin` as just integers.

**Comment by cat-in-136** [comment]
Oh, esp libraries are updated and  esp-idf-hal RMT related functions are now available!

Certainly your suggestion makes sense since esp-idf-sys.

I also agree that this is a good opportunity to do this, although it would also be destructive to API compatibility.

**Comment by faern** [comment]
I personally do not care about API stability. It's a very small library, and any user can probably easily migrate if it changes. You just released the breaking 0.6 version also, so do you care about API stability? The embedded ecosystem moves fast. So I'd rather be up to date with the latest and greatest.
